<a href="https://colab.research.google.com/github/fatoufall737/atelier-numpy-iot/blob/main/atelier_numpy_iot.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Contexte
Une entreprise dispose de plusieurs capteurs installés dans différents bâtiments. Les capteurs
mesurent régulièrement la température, l'humidité, la pression et la consommation énergétique.
Les données doivent être préparées et analysées avant d'être transmises à un futur système de
Machine Learning permettant de détecter des situations anormales
Partie 1 : Listes Python vs tableaux NumPy
On dispose des températures mesurées par un capteur : 24.5, 25.1, 26.3, 27.0 et 25.8
partie 1 ⁉
1) Créer une liste Python stockant ces températures;
2) Créer un tableau NumPy équivalent stockant ces températures ;
3) Effectuer une multiplication par 2 sur ces deux collections;
4) Quelle différence observe-t-on ?

In [1]:
import numpy as np

np.random.seed(42)

In [2]:
temperatures_liste = [24.5, 25.1, 26.3, 27.0, 25.8]
temperatures_liste  #creation d'une liste contenant les temperatures

[24.5, 25.1, 26.3, 27.0, 25.8]

In [3]:
#question 2 : crée le tableau NumPy équivalent, avec les mêmes valeurs :python

temperatures_array = np.array([24.5, 25.1, 26.3, 27.0, 25.8])
temperatures_array

array([24.5, 25.1, 26.3, 27. , 25.8])

In [4]:
#effectuer une multiplication par deux 2 sur ces deux collections
liste_x2 = temperatures_liste * 2
print("Liste * 2 :", liste_x2)

array_x2 = temperatures_array * 2
print("Array * 2 :", array_x2)

Liste * 2 : [24.5, 25.1, 26.3, 27.0, 25.8, 24.5, 25.1, 26.3, 27.0, 25.8]
Array * 2 : [49.  50.2 52.6 54.  51.6]


la difference observee est que :Sur une liste Python, l'opérateur * duplique la liste au lieu de multiplier les valeurs. Sur un tableau NumPy, * applique une multiplication élément par élément (vectorisée), ce qui est le comportement attendu pour du calcul scientifique.

Partie 2 – Création des données
1) Créer un tableau représentant les mesures de température de 10 capteurs, initialement à zéro.
2) Créer un tableau contenant 10 valeurs égales à 1.
3) Créer un tableau de 10 valeurs initialisées à 25.
4) Créer une matrice identité de taille 5 × 5.
5) Créer les 24 heures (de 0 à 23) de mesure d’une journée
6) Créer 10 valeurs régulièrement réparties entre 20 °C et 30 °C  
7) Créer aléatoirement les températures de 100 mesures, en rendant les résultats reproductibles

In [5]:
#creation d'un tableau representant les mesures de temperatures de 10 capteurs initialement a zero
capteurs_zero = np.zeros(10)
capteurs_zero

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
#creer un tableau contenant 10 valeurs egales a 1
valeurs_un = np.ones(10)
valeurs_un

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
#creer un tableau de 10 valeurs initialisees a 25
valeurs_25 = np.full(10, 25)
valeurs_25

array([25, 25, 25, 25, 25, 25, 25, 25, 25, 25])

In [ ]:
#creation d'une matrice identite de taille 5 fois 5
identite_5 = np.eye(5)
identite_5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
# creer les 24 heures de (0 a 23 )de mesure d'une journee
heures = np.arange(24)
heures

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [ ]:
#crée 10 valeurs régulièrement réparties entre 20°C et 30°C.
valeurs_reparties = np.linspace(20, 30, 10)
valeurs_reparties

array([20.        , 21.11111111, 22.22222222, 23.33333333, 24.44444444,
       25.55555556, 26.66666667, 27.77777778, 28.88888889, 30.        ])

In [ ]:
#creation aleatoire des temperatures de 100 mesures en rendant les resultats reproductibles
np.random.seed(42)
mesures_100 = np.random.uniform(low=15, high=35, size=100)
mesures_100[:10]  # aperçu des 10 premières valeurs

array([22.49080238, 34.01428613, 29.63987884, 26.97316968, 18.12037281,
       18.11989041, 16.16167224, 32.32352292, 27.02230023, 29.16145156])

Partie 3 – Exploration des tableaux
1) Créer aléatoirement un tableau représentant les 24 températures d'une journée :
2) Déterminer les propriétés suivantes du tableau
a) nombre de dimensions ;
b) nombre de valeurs ;
c) type des données ;
d) forme du tableau.

In [7]:
#crée aléatoirement un tableau représentant les 24 températures d'une journée.
np.random.seed(42)
temperatures_jour = np.random.uniform(low=15, high=35, size=24)
temperatures_jour

array([22.49080238, 34.01428613, 29.63987884, 26.97316968, 18.12037281,
       18.11989041, 16.16167224, 32.32352292, 27.02230023, 29.16145156,
       15.41168989, 34.39819704, 31.64885282, 19.24678221, 18.63649934,
       18.6680902 , 21.08484486, 25.49512863, 23.63890037, 20.8245828 ,
       27.23705789, 17.78987721, 20.84289297, 22.32723687])

In [ ]:
#détermine les propriétés du tableau temperatures_jour
print("a) Nombre de dimensions (ndim) :", temperatures_jour.ndim)
print("b) Nombre de valeurs (size)      :", temperatures_jour.size)
print("c) Type des données (dtype)      :", temperatures_jour.dtype)
print("d) Forme du tableau (shape)      :", temperatures_jour.shape)

a) Nombre de dimensions (ndim) : 1
b) Nombre de valeurs (size)      : 24
c) Type des données (dtype)      : float64
d) Forme du tableau (shape)      : (24,)


Partie 4 – Indexation et slicing
Considérant le tableau représentant les 24 températures d'une journée, afficher :
1) la première mesure ;  
2) la dernière mesure ;  
3) la température de 8h ;  
4) les températures de 8h à 12h ;  
5) les températures des 6 premières heures ;  
6) les températures des heures paires.

In [ ]:
#affichage la premiere mesure
premiere_mesure = temperatures_jour[0]
premiere_mesure

np.float64(22.49080237694725)

In [ ]:
#affichage de la derniere mesure
derniere_mesure = temperatures_jour[-1]
derniere_mesure

np.float64(22.327236865873836)

In [ ]:
#affichage de la temperature de 8h
temp_8h = temperatures_jour[8]
temp_8h

np.float64(27.022300234864176)

In [ ]:
# les temperatures de 8h a 13h
temp_8h_12h = temperatures_jour[8:13]
temp_8h_12h

array([27.02230023, 29.16145156, 15.41168989, 34.39819704, 31.64885282])

In [ ]:
#les temperatures des 6 premieres heures
temp_6_premieres_heures = temperatures_jour[:6]
temp_6_premieres_heures

array([22.49080238, 34.01428613, 29.63987884, 26.97316968, 18.12037281,
       18.11989041])

In [8]:
#les temperatures des heures paires
temp_heures_paires = temperatures_jour[::2]
temp_heures_paires

array([22.49080238, 29.63987884, 18.12037281, 16.16167224, 27.02230023,
       15.41168989, 31.64885282, 18.63649934, 21.08484486, 23.63890037,
       27.23705789, 20.84289297])

Partie 5 – Filtrage booléen
Considérant le tableau représentant les 24 températures d'une journée, on souhaite détecter les
situations inhabituelles.  
1) Afficher les températures supérieures à 30 °C
2) Afficher les températures « normales » càd comprises entre 20 °C et 30 °C
3) Supposons qu'une température supérieure à 35 °C soit considérée comme anormale.
Déterminer anomalies, un tableau de booléen précisant les anomalies
4) Déterminer le nombre de températures anormales à l’aide de la variable anomalies

In [10]:
# Afficher les températures supérieures à 30 °C
temp_sup_30 = temperatures_jour[temperatures_jour > 30]
temp_sup_30

array([34.01428613, 32.32352292, 34.39819704, 31.64885282])

In [11]:
#Afficher les températures « normales » càd comprises entre 20 °C et 30 °C
temp_normales = temperatures_jour[(temperatures_jour >= 20) & (temperatures_jour <= 30)]
temp_normales

array([22.49080238, 29.63987884, 26.97316968, 27.02230023, 29.16145156,
       21.08484486, 25.49512863, 23.63890037, 20.8245828 , 27.23705789,
       20.84289297, 22.32723687])

In [12]:
#suppose qu'une température supérieure à 35°C soit considérée comme anormale. Détermine anomalies, un tableau de booléens précisant les anomalies.
anomalies = temperatures_jour > 35
anomalies

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False])

In [13]:
#détermine le nombre de températures anormales à l'aide de la variable anomalies.
nb_anomalies = anomalies.sum()  # équivalent à np.sum(anomalies)
nb_anomalies

np.int64(0)

Partie 6 – Manipulation des dimensions
On suppose qu’on a 5 capteurs.  
1) Créer aléatoirement la matrice représentant les températures mesurées par ces capteurs durant
une journée
2) Transformer la matrice en un tableau unidimensionnel
3) Déterminer la transposée de la matrice
4) Extraire toutes les mesures du capteur 1 ;
5) Extraire toutes les mesures du capteur 5 ;
6) Extraire les mesures de tous les capteurs à 10h ;
7) Extraire les mesures des capteurs 2 à 4 entre 8h et 12h.

In [ ]:
#creation aleatoire de la matrice representant les temperatures mesurees par ces capteurs durant une journee
#(5 lignes = capteurs, 24 colonnes = heures).
np.random.seed(42)
temperatures_5capteurs = np.random.uniform(low=15, high=35, size=(5, 24))
temperatures_5capteurs

array([[22.49080238, 34.01428613, 29.63987884, 26.97316968, 18.12037281,
        18.11989041, 16.16167224, 32.32352292, 27.02230023, 29.16145156,
        15.41168989, 34.39819704, 31.64885282, 19.24678221, 18.63649934,
        18.6680902 , 21.08484486, 25.49512863, 23.63890037, 20.8245828 ,
        27.23705789, 17.78987721, 20.84289297, 22.32723687],
       [24.12139968, 30.70351923, 18.99347564, 25.28468877, 26.84829138,
        15.92900825, 27.15089704, 18.41048247, 16.30103186, 33.97771075,
        34.31264066, 31.16794696, 21.09227538, 16.95344228, 28.68466053,
        23.80304987, 17.4407647 , 24.9035382 , 15.68777042, 33.18640804,
        20.17559963, 28.25044569, 21.23422152, 25.40136042],
       [25.93420559, 18.69708911, 34.39169256, 30.50265647, 33.78997883,
        32.89654701, 26.95799958, 33.4374847 , 16.76985004, 18.91965725,
        15.90454578, 21.50660662, 22.77354579, 20.42698064, 31.57475018,
        22.13506653, 20.61869019, 25.85392166, 17.8184845 , 31.04393962,
  

In [ ]:
#transformer la matrice en un tableau unidimentionnel
temperatures_1d = temperatures_5capteurs.flatten()
temperatures_1d.shape

(120,)

In [ ]:
#determiner la transposee de la matrice
temperatures_transposee = temperatures_5capteurs.T
temperatures_transposee.shape  # (24, 5) au lieu de (5, 24)

(24, 5)

In [ ]:
#extraction de toutes les mesures du capteur 1
capteur_1 = temperatures_5capteurs[0]
capteur_1

array([22.49080238, 34.01428613, 29.63987884, 26.97316968, 18.12037281,
       18.11989041, 16.16167224, 32.32352292, 27.02230023, 29.16145156,
       15.41168989, 34.39819704, 31.64885282, 19.24678221, 18.63649934,
       18.6680902 , 21.08484486, 25.49512863, 23.63890037, 20.8245828 ,
       27.23705789, 17.78987721, 20.84289297, 22.32723687])

In [ ]:
#extrais les mesures de tous les capteurs à 10h.
mesures_10h = temperatures_5capteurs[:, 10]
mesures_10h

array([15.41168989, 34.31264066, 15.90454578, 21.6179605 , 23.20765846])

In [ ]:
#Extraire les mesures des capteurs 2 à 4 entre 8h et 12h.
# capteurs 2 à 4 -> index 1 à 3 (inclus) ; heures 8h à 12h -> index 8 à 12 (inclus)
mesures_capteurs2a4_8h12h = temperatures_5capteurs[1:4, 8:13]
mesures_capteurs2a4_8h12h

array([[16.30103186, 33.97771075, 34.31264066, 31.16794696, 21.09227538],
       [16.76985004, 18.91965725, 15.90454578, 21.50660662, 22.77354579],
       [32.26206852, 27.46596254, 21.6179605 , 16.27116701, 21.21964643]])

Partie 7 – Concaténation
On suppose qu’on a un 2nd bâtiment avec 3 capteurs.  
1) Créer aléatoirement la matrice représentant les températures mesurées par les 3 capteurs
durant une journée
2) Déterminer de deux manières différentes la matrice qui fusionne les températures mesurées par
les 8 capteurs durant une journée

In [14]:
#crée aléatoirement la matrice représentant les températures mesurées par les 3 capteurs du 2ᵉ bâtiment durant une journée.
np.random.seed(7)  # seed différent du bâtiment 1 pour avoir des données distinctes
temperatures_batiment2 = np.random.uniform(low=15, high=35, size=(3, 24))
temperatures_batiment2

array([[16.52616579, 30.59837584, 23.76818463, 29.46930356, 34.55979024,
        25.76991741, 25.02240927, 16.44102267, 20.3687796 , 24.99765002,
        28.58459992, 31.07478072, 22.61882266, 16.31872694, 20.76291199,
        33.19187055, 19.26770707, 24.04247924, 33.62412039, 15.49798455,
        27.01097835, 34.00259001, 19.60605758, 25.96979838],
       [33.1825675 , 17.66338892, 25.46825161, 30.00819718, 28.38026482,
        24.35505719, 19.09698181, 24.81531778, 22.44769379, 24.5480231 ,
        22.31780772, 31.75835989, 30.37295013, 21.27989354, 26.45250665,
        20.52098097, 24.05685865, 22.05956732, 28.14798926, 22.40702166,
        24.18185956, 29.38648245, 23.25983658, 33.12846538],
       [18.60903238, 29.82237746, 23.44748087, 23.52907145, 27.68759737,
        25.45812402, 23.29771957, 15.02853761, 16.84524692, 29.18788787,
        25.48691194, 28.92320927, 34.10936646, 28.65827709, 16.06257381,
        21.1770537 , 26.85189375, 19.70240815, 34.29941999, 33.90096448,
  

In [ ]:
#ici on determine deux methodes differentes de déterminer la matrice qui fusionne les températures mesurées par les 8 capteurs (5 du bâtiment 1 + 3 du bâtiment 2) durant une journée.

# Méthode 1 : np.concatenate sur l'axe 0 (empilement des lignes/capteurs)
temperatures_8capteurs_v1 = np.concatenate((temperatures_5capteurs, temperatures_batiment2), axis=0)

# Méthode 2 : np.vstack, équivalent pour un empilement vertical
temperatures_8capteurs_v2 = np.vstack((temperatures_5capteurs, temperatures_batiment2))

print(temperatures_8capteurs_v1.shape, temperatures_8capteurs_v2.shape)
np.array_equal(temperatures_8capteurs_v1, temperatures_8capteurs_v2)

(8, 24) (8, 24)


True

Partie 8 : Calcul scientifique
Considérons le tableau représentant les 24 températures du 1er bâtiment.
1) Pour les températures calculer le minimum, le maximum, la somme, la moyenne, la médiane, la
variance et l’écart-type
2) Standardiser le tableau des températures puis vérifier les valeurs de la moyenne et de l’écart
type du tableau standardisé
3) Normaliser (Min-Max) le tableau des températures puis vérifier les valeurs du tableau normalisé
4) Convertir le tableau initial en Fahrenheit

In [ ]:
#Pour les températures calculer le minimum, le maximum, la somme, la moyenne, la médiane, la variance et l’écart-type
# en utilisant les temperatures_jour (les 24 températures du 1ᵉʳ bâtiment).
print("Minimum   :", temperatures_jour.min())
print("Maximum   :", temperatures_jour.max())
print("Somme     :", temperatures_jour.sum())
print("Moyenne   :", temperatures_jour.mean())
print("Médiane   :", np.median(temperatures_jour))
print("Variance  :", temperatures_jour.var())
print("Écart-type:", temperatures_jour.std())

Minimum   : 15.411689885916049
Maximum   : 34.39819704323989
Somme     : 571.2779803031808
Moyenne   : 23.8032491792992
Médiane   : 22.409019621410543
Variance  : 32.53568144079373
Écart-type: 5.7040057363920775


In [ ]:
# Standardisation du tableau, des températures puis on passe a la vérification des valeurs de la moyenne et de l’écart type du tableau standardisé
temperatures_standardisees = (temperatures_jour - temperatures_jour.mean()) / temperatures_jour.std()

print("Moyenne après standardisation   :", round(temperatures_standardisees.mean(), 10))
print("Écart-type après standardisation:", round(temperatures_standardisees.std(), 10))
# La moyenne doit être ~0 et l'écart-type ~1

Moyenne après standardisation   : 0.0
Écart-type après standardisation: 1.0


In [ ]:
#Normalisation de (Min-Max) le tableau des températures puis vérifier les valeurs du tableau normalisé
temperatures_normalisees = (temperatures_jour - temperatures_jour.min()) / (temperatures_jour.max() - temperatures_jour.min())

print("Minimum après normalisation :", temperatures_normalisees.min())
print("Maximum après normalisation :", temperatures_normalisees.max())
# Toutes les valeurs doivent être comprises entre 0 et 1

Minimum après normalisation : 0.0
Maximum après normalisation : 1.0


In [ ]:
#Convertion du tableau initial en Fahrenheit
temperatures_fahrenheit = temperatures_jour * 9/5 + 32
temperatures_fahrenheit

array([72.48344428, 93.22571503, 85.35178191, 80.55170543, 64.61667106,
       64.61580273, 61.09101004, 90.18234125, 80.64014042, 84.4906128 ,
       59.74104179, 93.91675468, 88.96793507, 66.64420798, 65.54569882,
       65.60256235, 69.95272075, 77.89123154, 74.55002067, 69.48424905,
       81.02670421, 64.02177898, 69.51720735, 72.18902636])

La formule pour convertir Celsius → Fahrenheit est :

°F = °C × 9/5 + 32

C'est exactement ce que fait la ligne de code qu'on vient d'exécuter — elle applique cette formule à chacune des 24 températures du tableau d'un coup, grâce au calcul vectorisé de NumPy (pas besoin de boucle for).

Partie 9 : Broadcasting

1. Créer aléatoirement la matrice temperatures_3x3 représentant les températures mesurées à 10h, 11h et 12h dans le 2nd bâtiment
2. Supposons que les valeurs de calibration des capteurs soient stockées dans le tableau
correction = np.array([1, -0.5, 0.2])

Appliquer automatiquement les corrections pour trouver les mesures corrigées
     mesures_corrigees = temperatures_3x3 + correction

In [15]:
#creation aleatoire de la matrice temperature 3fois 3 ...
np.random.seed(42)
# 3 heures (10h, 11h, 12h) en lignes, 3 capteurs du bâtiment 2 en colonnes
temperatures_3x3 = np.random.uniform(low=15, high=35, size=(3, 3))
temperatures_3x3.shape  # (3 heures, 3 capteurs)

(3, 3)

In [16]:
#Appliquer automatiquement les corrections pour trouver les mesures corrigées mesures_corrigees = temperatures_3x3 + correction
correction = np.array([1, -0.5, 0.2])  # une correction par capteur

mesures_corrigees = temperatures_3x3 + correction
mesures_corrigees

array([[23.49080238, 33.51428613, 29.83987884],
       [27.97316968, 17.62037281, 18.31989041],
       [17.16167224, 31.82352292, 27.22230023]])