<a href="https://colab.research.google.com/github/fatoufall737/atelier-numpy-iot/blob/main/atelier_numpy_iot.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Contexte
Une entreprise dispose de plusieurs capteurs installés dans différents bâtiments. Les capteurs
mesurent régulièrement la température, l'humidité, la pression et la consommation énergétique.
Les données doivent être préparées et analysées avant d'être transmises à un futur système de
Machine Learning permettant de détecter des situations anormales
Partie 1 : Listes Python vs tableaux NumPy
On dispose des températures mesurées par un capteur : 24.5, 25.1, 26.3, 27.0 et 25.8
partie 1 ⁉
1) Créer une liste Python stockant ces températures;
2) Créer un tableau NumPy équivalent stockant ces températures ;
3) Effectuer une multiplication par 2 sur ces deux collections;
4) Quelle différence observe-t-on ?

In [1]:
import numpy as np

np.random.seed(42)

In [2]:
temperatures_liste = [24.5, 25.1, 26.3, 27.0, 25.8]
temperatures_liste  #creation d'une liste contenant les temperatures

[24.5, 25.1, 26.3, 27.0, 25.8]

In [3]:
#question 2 : crée le tableau NumPy équivalent, avec les mêmes valeurs :python

temperatures_array = np.array([24.5, 25.1, 26.3, 27.0, 25.8])
temperatures_array

array([24.5, 25.1, 26.3, 27. , 25.8])

In [4]:
#effectuer une multiplication par deux 2 sur ces deux collections
liste_x2 = temperatures_liste * 2
print("Liste * 2 :", liste_x2)

array_x2 = temperatures_array * 2
print("Array * 2 :", array_x2)

Liste * 2 : [24.5, 25.1, 26.3, 27.0, 25.8, 24.5, 25.1, 26.3, 27.0, 25.8]
Array * 2 : [49.  50.2 52.6 54.  51.6]


la difference observee est que :Sur une liste Python, l'opérateur * duplique la liste au lieu de multiplier les valeurs. Sur un tableau NumPy, * applique une multiplication élément par élément (vectorisée), ce qui est le comportement attendu pour du calcul scientifique.

Partie 2 – Création des données
1) Créer un tableau représentant les mesures de température de 10 capteurs, initialement à zéro.
2) Créer un tableau contenant 10 valeurs égales à 1.
3) Créer un tableau de 10 valeurs initialisées à 25.
4) Créer une matrice identité de taille 5 × 5.
5) Créer les 24 heures (de 0 à 23) de mesure d’une journée
6) Créer 10 valeurs régulièrement réparties entre 20 °C et 30 °C  
7) Créer aléatoirement les températures de 100 mesures, en rendant les résultats reproductibles

In [5]:
#creation d'un tableau representant les mesures de temperatures de 10 capteurs initialement a zero
capteurs_zero = np.zeros(10)
capteurs_zero

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
#creer un tableau contenant 10 valeurs egales a 1
valeurs_un = np.ones(10)
valeurs_un

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
#creer un tableau de 10 valeurs initialisees a 25
valeurs_25 = np.full(10, 25)
valeurs_25

array([25, 25, 25, 25, 25, 25, 25, 25, 25, 25])

In [ ]:
#creation d'une matrice identite de taille 5 fois 5
identite_5 = np.eye(5)
identite_5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
# creer les 24 heures de (0 a 23 )de mesure d'une journee
heures = np.arange(24)
heures

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [ ]:
#crée 10 valeurs régulièrement réparties entre 20°C et 30°C.
valeurs_reparties = np.linspace(20, 30, 10)
valeurs_reparties

array([20.        , 21.11111111, 22.22222222, 23.33333333, 24.44444444,
       25.55555556, 26.66666667, 27.77777778, 28.88888889, 30.        ])

In [ ]:
#creation aleatoire des temperatures de 100 mesures en rendant les resultats reproductibles
np.random.seed(42)
mesures_100 = np.random.uniform(low=15, high=35, size=100)
mesures_100[:10]  # aperçu des 10 premières valeurs

array([22.49080238, 34.01428613, 29.63987884, 26.97316968, 18.12037281,
       18.11989041, 16.16167224, 32.32352292, 27.02230023, 29.16145156])

Partie 3 – Exploration des tableaux
1) Créer aléatoirement un tableau représentant les 24 températures d'une journée :
2) Déterminer les propriétés suivantes du tableau
a) nombre de dimensions ;
b) nombre de valeurs ;
c) type des données ;
d) forme du tableau.

In [7]:
#crée aléatoirement un tableau représentant les 24 températures d'une journée.
np.random.seed(42)
temperatures_jour = np.random.uniform(low=15, high=35, size=24)
temperatures_jour

array([22.49080238, 34.01428613, 29.63987884, 26.97316968, 18.12037281,
       18.11989041, 16.16167224, 32.32352292, 27.02230023, 29.16145156,
       15.41168989, 34.39819704, 31.64885282, 19.24678221, 18.63649934,
       18.6680902 , 21.08484486, 25.49512863, 23.63890037, 20.8245828 ,
       27.23705789, 17.78987721, 20.84289297, 22.32723687])

In [ ]:
#détermine les propriétés du tableau temperatures_jour
print("a) Nombre de dimensions (ndim) :", temperatures_jour.ndim)
print("b) Nombre de valeurs (size)      :", temperatures_jour.size)
print("c) Type des données (dtype)      :", temperatures_jour.dtype)
print("d) Forme du tableau (shape)      :", temperatures_jour.shape)

a) Nombre de dimensions (ndim) : 1
b) Nombre de valeurs (size)      : 24
c) Type des données (dtype)      : float64
d) Forme du tableau (shape)      : (24,)


Partie 4 – Indexation et slicing
Considérant le tableau représentant les 24 températures d'une journée, afficher :
1) la première mesure ;  
2) la dernière mesure ;  
3) la température de 8h ;  
4) les températures de 8h à 12h ;  
5) les températures des 6 premières heures ;  
6) les températures des heures paires.

In [ ]:
#affichage la premiere mesure
premiere_mesure = temperatures_jour[0]
premiere_mesure

np.float64(22.49080237694725)

In [ ]:
#affichage de la derniere mesure
derniere_mesure = temperatures_jour[-1]
derniere_mesure

np.float64(22.327236865873836)

In [ ]:
#affichage de la temperature de 8h
temp_8h = temperatures_jour[8]
temp_8h

np.float64(27.022300234864176)

In [ ]:
# les temperatures de 8h a 13h
temp_8h_12h = temperatures_jour[8:13]
temp_8h_12h

array([27.02230023, 29.16145156, 15.41168989, 34.39819704, 31.64885282])

In [ ]:
#les temperatures des 6 premieres heures
temp_6_premieres_heures = temperatures_jour[:6]
temp_6_premieres_heures

array([22.49080238, 34.01428613, 29.63987884, 26.97316968, 18.12037281,
       18.11989041])

In [8]:
#les temperatures des heures paires
temp_heures_paires = temperatures_jour[::2]
temp_heures_paires

array([22.49080238, 29.63987884, 18.12037281, 16.16167224, 27.02230023,
       15.41168989, 31.64885282, 18.63649934, 21.08484486, 23.63890037,
       27.23705789, 20.84289297])